// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAu36TlGWPT2jXFLbIqT0wDbFnJaALvUk',
    appId: '1:27401901723:web:21ad8a7791fca854ea183e',
    messagingSenderId: '27401901723',
    projectId: 'wolfbite-465ae',
    authDomain: 'wolfbite-465ae.firebaseapp.com',
    storageBucket: 'wolfbite-465ae.firebasestorage.app',
    measurementId: 'G-JF4FHQ9H13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpBoO_wjk10NiYxNT4cwPGR_DQW4xxy1Q',
    appId: '1:27401901723:android:36b7c2853729c5e6ea183e',
    messagingSenderId: '27401901723',
    projectId: 'wolfbite-465ae',
    storageBucket: 'wolfbite-465ae.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAu36TlGWPT2jXFLbIqT0wDbFnJaALvUk',
    appId: '1:27401901723:web:27c1f229076aed23ea183e',
    messagingSenderId: '27401901723',
    projectId: 'wolfbite-465ae',
    authDomain: 'wolfbite-465ae.firebaseapp.com',
    storageBucket: 'wolfbite-465ae.firebasestorage.app',
    measurementId: 'G-33KP571THK',
  );
}
