// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp6VD02fBapiFWE1BmDdZxf5ITTFdqUUA',
    appId: '1:644721227450:web:a8899841efce796a6f7483',
    messagingSenderId: '644721227450',
    projectId: 'se25fall-g1-proj3',
    authDomain: 'se25fall-g1-proj3.firebaseapp.com',
    storageBucket: 'se25fall-g1-proj3.firebasestorage.app',
    measurementId: 'G-KHW2WXS915',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5zdyMhxx5PjbPVO-Bavmx3KidMuzqtWk',
    appId: '1:644721227450:android:6659f6001349eb656f7483',
    messagingSenderId: '644721227450',
    projectId: 'se25fall-g1-proj3',
    storageBucket: 'se25fall-g1-proj3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp6VD02fBapiFWE1BmDdZxf5ITTFdqUUA',
    appId: '1:644721227450:web:1fa1a0b2a75118b16f7483',
    messagingSenderId: '644721227450',
    projectId: 'se25fall-g1-proj3',
    authDomain: 'se25fall-g1-proj3.firebaseapp.com',
    storageBucket: 'se25fall-g1-proj3.firebasestorage.app',
    measurementId: 'G-KFLKKZWLER',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBcZLt0VsrSLd6izv1nxIzCZ9pftlawto',
    appId: '1:644721227450:ios:6b080e496a3e93586f7483',
    messagingSenderId: '644721227450',
    projectId: 'se25fall-g1-proj3',
    storageBucket: 'se25fall-g1-proj3.firebasestorage.app',
    iosBundleId: 'com.example.wolfbite',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBcZLt0VsrSLd6izv1nxIzCZ9pftlawto',
    appId: '1:644721227450:ios:6b080e496a3e93586f7483',
    messagingSenderId: '644721227450',
    projectId: 'se25fall-g1-proj3',
    storageBucket: 'se25fall-g1-proj3.firebasestorage.app',
    iosBundleId: 'com.example.wolfbite',
  );
